import { TextWeight } from './typography-types.ts';

// Mapping weight number to font family name
export const weightToFontFamily: Record<TextWeight, string> = {
  300: 'Manrope-Light',
  400: 'Manrope-Regular',
  500: 'Manrope-Medium',
  600: 'Manrope-SemiBold',
  700: 'Manrope-Bold',
  800: 'Manrope-ExtraBold',
};

export const IconEnum = {
  Back: '\ue900',
  BangStar: '\ue901',
  Check: '\ue902',
  ChevronDown: '\ue903',
  ChevronLeft: '\ue904',
  ChevronRight: '\ue905',
  ChevronUp: '\ue906',
  Close: '\ue907',
  Edit: '\ue908',
  Export: '\ue909',
  Import: '\ue90a',
  Refresh: '\ue90b',
  Save: '\ue90c',
  Star: '\ue90d',
  Tasks: '\ue90e',
  Trash: '\ue90f',
  Plus: '',
  BasketballFill: '\ue910',
  BeerFill: '\ue911',
  CalendarFill: '\ue912',
  ColorFill: '\ue913',
  DumbFill: '\ue914',
  HockeyFill: '\ue915',
  ImageFill: '\ue916',
  KabaddiFill: '\ue917',
  LowKickFill: '\ue918',
  MedalFill: '\ue919',
  MotorshipFill: '\ue91a',
  ProgressFill: '\ue91b',
  SettingsFill: '\ue91c',
  SoccerFill: '\ue91d',
  SportsFill: '\ue91e',
  StarFill: '\ue91f',
  SwimFill: '\ue920',
  TasksFill: '\ue921',
  TimeFill: '\ue922',
  UserFill: '\ue923',
  VideoFill: '\ue924',
  VolleyballFill: '\ue925',
  CigareFill: '\ue926',
  DanceFill: '\ue927',
  EducationFill: '\ue928',
  FatFill: '\ue929',
  FoodFill: '\ue92a',
  PillFill: '\ue92b',
  RunFill: '\ue92c',
  SneakerFill: '\ue92d',
  SquatFill: '\ue92e',
  WeedFill: '\ue92f',
  MoonFill: '',
  SunFill: '',
  FireFill: '',
  WineFill: '',
} as const;
export type IconEnum = (typeof IconEnum)[keyof typeof IconEnum];
